name: Build and greet using environment variables

on:
  push
env:
  GLOBAL_MESSAGE: "This is a global message"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: python -c "print(f'${{env.GLOBAL_MESSAGE}}')"
      
  greet:
    runs-on: ubuntu-latest

    env:
      GREETING_MESSAGE: "Hello World"

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: python -c "print(f'${{env.GLOBAL_MESSAGE}}')"
