name: Build and greet using environment variables

on:
  push
env:
  GLOBAL_MESSAGE: "This is a global message"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: run bash
     
    - run: echo ${{env.GLOBAL_MESSAGE}}
    
  greet:
    runs-on: ubuntu-latest

    env:
      GREETING_MESSAGE: "Hello World"

    steps:
    - name: run bash
     
    - run: echo ${{env.GLOBAL_MESSAGE}}
      
